version: '3.9'

services:
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  publisher:
    build:
      context: publish
      dockerfile: Dockerfile
    container_name: publisher
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
      - mongodb

  subscriber_interesting:
    build:
      context: subscribe
      dockerfile: interesting.Dockerfile
    container_name: subscriber_interesting
    ports:
      - "8002:8002"
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_HOST=mongodb
    depends_on:
      - kafka
      - mongodb

  subscriber_not_interesting:
    build:
      context: subscribe
      dockerfile: not_interesting.Dockerfile
    container_name: subscriber_not_interesting
    ports:
      - "8003:8003"
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_HOST=mongodb
    depends_on:
      - kafka
      - mongodb

volumes:
  mongo_data: